"""PlatformIO pre-build hook: turn the vendored dashboard into a C source.

The hub role serves web/dashboard.html; ws_mqtt_bridge.c links it as the byte
array `dashboard_html` / `dashboard_html_len`. We generate that array here
instead of using an objcopy/.S embed, which PlatformIO's SCons build doesn't
reliably wire into the link (it emits the .S but never assembles/links it).

Stored GZIPPED and served with Content-Encoding: gzip, exactly as embed_ide.py
already does for the bundle next door — the browser inflates, the chip never
does. This array is the single biggest thing in the image and it sat here raw
while its sibling was already compressed. That is not a micro-optimization at
4 MB flash: it is most of the difference between the unified image fitting two
OTA slots or not, and it buys the same win over the AP radio that pi/CLAUDE.md
already measured into starvation.

gzip mtime is pinned to 0 so regeneration is deterministic — otherwise every
build would rewrite the .c and defeat the write-only-on-change incrementality
below (embed_ide.py hit this first; same trap, same fix).

Runs before every build (platformio.ini `extra_scripts = pre:...`); writes
src/dashboard_html.c only when the content changed, so it never dirties the
tree or forces a needless rebuild. The .c is gitignored — this hook is the
single generator, web/dashboard.html (vendored from better-robotics/hub) is the
source of truth.
"""
import gzip
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

# __file__ isn't defined in SCons's exec context — locate paths from the project
# root PlatformIO hands us instead.
PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
SRC = os.path.join(PROJECT_DIR, "web", "dashboard.html")
DST = os.path.join(PROJECT_DIR, "src", "dashboard_html.c")


def generate():
    if not os.path.exists(SRC):
        raise SystemExit(
            "embed_dashboard: %s missing — run tools/sync-dashboard.sh "
            "(vendor it from the hub repo) first" % SRC
        )
    with open(SRC, "rb") as f:
        data = f.read()

    # mtime=0: see the determinism note above — a timestamp in the gzip header
    # would make every build emit a different .c and rewrite it unconditionally.
    body_bytes = gzip.compress(data, compresslevel=9, mtime=0)

    body = ",".join(str(b) for b in body_bytes)
    out = (
        "/* GENERATED by tools/embed_dashboard.py from web/dashboard.html — do "
        "not edit.\n"
        " * The hub role's embedded classroom dashboard (ws_mqtt_bridge.c),\n"
        " * stored gzipped: the handler sets Content-Encoding: gzip and the\n"
        " * browser inflates. dashboard_html_len is the COMPRESSED length —\n"
        " * it is what the handler sends, never the original size. */\n"
        "const unsigned char dashboard_html[] = {%s};\n"
        "const unsigned int dashboard_html_len = %d;\n" % (body, len(body_bytes))
    )

    # Write only on change: keeps the build incremental and the tree clean.
    if os.path.exists(DST):
        with open(DST, "r") as f:
            if f.read() == out:
                return
    with open(DST, "w") as f:
        f.write(out)
    print(
        "embed_dashboard: regenerated src/dashboard_html.c (%d KB raw -> %d KB "
        "gzipped)" % (len(data) // 1024, len(body_bytes) // 1024)
    )


generate()
