"""PlatformIO pre-build hook: turn web/ into C sources the hub role serves.

Was embed_dashboard.py while the dashboard was the only embedded page; renamed
when the IDE loader shell joined it — one hook owns the web/→C seam.

Each entry below becomes a generated .c holding the file as a byte array the
firmware links (ws_mqtt_bridge.c declares the externs). We generate arrays
instead of using an objcopy/.S embed, which PlatformIO's SCons build doesn't
reliably wire into the link (it emits the .S but never assembles/links it).

Stored GZIPPED and served with Content-Encoding: gzip — the browser inflates,
the chip never does. The dashboard array is the single biggest thing in the
image; compressing it is most of the difference between the unified image
fitting two OTA slots or not. The shell is ~2 KB either way, but one seam,
one shape.

gzip mtime is pinned to 0 so regeneration is deterministic — otherwise every
build would rewrite the .c files and defeat the write-only-on-change
incrementality below.

Runs before every build (platformio.ini `extra_scripts = pre:...`); writes
each .c only when its content changed, so it never dirties the tree or forces
a needless rebuild. The .c files are gitignored — this hook is the single
generator; web/ (vendored: dashboard.html from better-robotics/hub,
ide_shell.html from better-robotics/ide) is the source of truth.
"""
import gzip
import hashlib
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

# __file__ isn't defined in SCons's exec context — locate paths from the project
# root PlatformIO hands us instead.
PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821

# (web source, generated .c, symbol prefix, sync script to name in the error)
FILES = [
    ("dashboard.html", "dashboard_html.c", "dashboard_html", "tools/sync-dashboard.sh"),
    ("ide_shell.html", "ide_shell_html.c", "ide_shell_html", "tools/sync-ide-shell.sh"),
]


def generate(src_name, dst_name, symbol, sync_hint):
    src = os.path.join(PROJECT_DIR, "web", src_name)
    dst = os.path.join(PROJECT_DIR, "src", dst_name)
    if not os.path.exists(src):
        raise SystemExit(
            "embed_web: %s missing — run %s (vendor it) first" % (src, sync_hint)
        )
    with open(src, "rb") as f:
        data = f.read()

    # mtime=0: see the determinism note above — a timestamp in the gzip header
    # would make every build emit a different .c and rewrite it unconditionally.
    body_bytes = gzip.compress(data, compresslevel=9, mtime=0)

    # Strong ETag = content hash of the compressed bytes (what the handler
    # actually sends). Changes only when the page changes, i.e. on OTA — so a
    # browser's If-None-Match turns every reload into a 304 instead of a
    # full-blob transfer over the classroom radio.
    etag = hashlib.sha256(body_bytes).hexdigest()[:16]

    body = ",".join(str(b) for b in body_bytes)
    out = (
        "/* GENERATED by tools/embed_web.py from web/%s — do not edit.\n"
        " * Served by the hub role (ws_zenoh_bridge.c), stored gzipped: the\n"
        " * handler sets Content-Encoding: gzip and the browser inflates.\n"
        " * %s_len is the COMPRESSED length — it is what the handler sends,\n"
        " * never the original size. %s_etag is quoted, ready for the header. */\n"
        "const unsigned char %s[] = {%s};\n"
        "const unsigned int %s_len = %d;\n"
        'const char %s_etag[] = "\\"%s\\"";\n'
        % (src_name, symbol, symbol, symbol, body, symbol, len(body_bytes),
           symbol, etag)
    )

    # Write only on change: keeps the build incremental and the tree clean.
    if os.path.exists(dst):
        with open(dst, "r") as f:
            if f.read() == out:
                return
    with open(dst, "w") as f:
        f.write(out)
    print(
        "embed_web: regenerated src/%s (%d KB raw -> %d KB gzipped)"
        % (dst_name, len(data) // 1024, len(body_bytes) // 1024)
    )


for entry in FILES:
    generate(*entry)
