"""PlatformIO pre-build hook: turn the vendored IDE bundle into a C source.

Sibling of embed_dashboard.py (same rationale: a generated .c compiled as an
ordinary source, because PlatformIO's SCons build won't link an objcopy/.S
embed). Walks web/ide/ (vendored from better-robotics/ide's ide-esp32 release
asset by tools/sync-ide.sh), gzips every file, and emits src/ide_bundle.c —
the path/type/data table ide_bundle.h declares and ws_mqtt_bridge.c serves at
/ide/* with Content-Encoding: gzip.

gzip mtime is pinned to 0 so regeneration is deterministic — otherwise every
build would rewrite the .c and defeat the write-only-on-change incrementality.
"""
import gzip
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
SRC_DIR = os.path.join(PROJECT_DIR, "web", "ide")
DST = os.path.join(PROJECT_DIR, "src", "ide_bundle.c")

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    # .mjs must be JS and .wasm application/wasm, or the browser refuses the
    # ES-module import / streaming-compile of the MicroPython runtime.
    ".mjs": "text/javascript; charset=utf-8",
    ".wasm": "application/wasm",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".gif": "image/gif",
    ".mp3": "audio/mpeg",
    ".ogg": "audio/ogg",
    ".wav": "audio/wav",
}


def generate():
    if not os.path.isdir(SRC_DIR):
        raise SystemExit(
            "embed_ide: %s missing — run tools/sync-ide.sh (vendor the ESP32 "
            "bundle from better-robotics/ide's release) first" % SRC_DIR
        )

    files = []
    for root, _dirs, names in os.walk(SRC_DIR):
        for name in sorted(names):
            if name.startswith("."):
                continue  # sync metadata (.tag), not content
            full = os.path.join(root, name)
            rel = os.path.relpath(full, SRC_DIR).replace(os.sep, "/")
            files.append((rel, full))
    files.sort()

    arrays, entries, raw_total, gz_total = [], [], 0, 0
    for i, (rel, full) in enumerate(files):
        with open(full, "rb") as f:
            data = f.read()
        gz = gzip.compress(data, compresslevel=9, mtime=0)
        raw_total += len(data)
        gz_total += len(gz)
        ext = os.path.splitext(rel)[1].lower()
        ctype = CONTENT_TYPES.get(ext, "application/octet-stream")
        arrays.append(
            "static const unsigned char f%d[] = {%s};"
            % (i, ",".join(str(b) for b in gz))
        )
        entries.append('{"/ide/%s", "%s", f%d, %d}' % (rel, ctype, i, len(gz)))

    out = (
        "/* GENERATED by tools/embed_ide.py from web/ide/ — do not edit.\n"
        " * The embedded block IDE, one gzip blob per file (ide_bundle.h). */\n"
        '#include "ide_bundle.h"\n'
        "%s\n"
        "const ide_file_t ide_files[] = {%s};\n"
        "const unsigned int ide_files_count = %d;\n"
        % ("\n".join(arrays), ",".join(entries), len(files))
    )

    # Write only on change: keeps the build incremental and the tree clean.
    if os.path.exists(DST):
        with open(DST, "r") as f:
            if f.read() == out:
                return
    with open(DST, "w") as f:
        f.write(out)
    print(
        "embed_ide: regenerated src/ide_bundle.c (%d files, %d KB raw -> %d KB gzipped)"
        % (len(files), raw_total // 1024, gz_total // 1024)
    )


generate()
